create table if not exists public.player_level_scores (
  id bigint generated by default as identity primary key,
  player_id text not null,
  player_name text not null,
  level_id integer not null check (level_id between 1 and 10),
  hints integer not null check (hints between 0 and 3),
  time integer not null check (time >= 0),
  moves integer not null check (moves >= 0),
  stars integer not null check (stars between 1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(player_id, level_id)
);

create index if not exists idx_player_level_scores_player_id
  on public.player_level_scores(player_id);

alter table public.player_level_scores enable row level security;

revoke all on table public.player_level_scores from anon, authenticated;

-- The public website never talks to the table directly.
-- Vercel serverless functions use SUPABASE_SECRET_KEY (or legacy service role key)
-- to read/write ranking data server-side.
